---
title: "R Data Viz"
output: html_document
---
# Airline Sentiment Data Visualization

```{r message=FALSE}
library(dplyr)
library(ggmap)
library(stringr)
library(tidytext)
library(leaflet)
library(ggplot2)
library(wordcloud)
library(knitr)
library(rmarkdown)
```

## Load Data
```{r }
tweet_data <- read.csv(file="/home/cdsw/data/Tweets.csv")
```

## Show tweet table
```{r }
paged_table(head(tweet_data, n = 100))
```

## Show table of positive vs negative tweets by airline
```{r echo=FALSE}
tweet_data %>%
    group_by(airline,airline_sentiment) %>%
    summarise(n()) %>%
    paged_table()

tweet_ratings <- tweet_data %>%
    group_by(airline,airline_sentiment)
```

## Plot positive vs negative tweets by airline
```{r  echo=FALSE}
s <- ggplot(tweet_ratings, aes(airline, fill = airline_sentiment)) + geom_bar(position = "fill")

cbPalette <- c("#ef8a62", "#f7f7f7", "#67a9cf")
s + scale_fill_manual(values=cbPalette)
```

## Plot number of tweets by location
```{r echo=FALSE}
load("/home/cdsw/dataviz/top_locations.rda")

as.data.frame(table(tweet_data['tweet_location'])) %>%
  arrange(desc(Freq)) %>%
  filter(Freq > 50) %>%
  slice(2:100) %>%
  paged_table()

leaflet(
  top_locs_with_name %>%
  slice(2:100) %>%
  group_by(long = lon,lat) %>%
  summarise(count = sum(n))
  ) %>%
  addTiles() %>%
  addCircleMarkers(
    radius = ~count/40,
    stroke = FALSE,
    fillOpacity = 0.5
  )
```

## Tokenize the words into a corpus
```{r  echo=FALSE}
data(stop_words)

airlines = tibble(text = c("united","usairways","americanair","southwestair","jetblue","virginamerica"))

text_df <- tibble(line = 1:length(as.character(tweet_data$text)), text = as.character(tweet_data$text))

text_df <- text_df %>%
  mutate(text = str_replace_all(text, "https://t.co/[A-Za-z\\d]+|http://[A-Za-z\\d]+|&amp;|&lt;|&gt;|RT|https", "")) %>%
  unnest_tokens(word, text) #, token = "regex", pattern = reg_words)

text_df <- text_df %>% anti_join(stop_words)
text_df <- text_df %>% anti_join(airlines,by = c("word" = "text"))
```

## Plot word count frequency
```{r}
text_df %>%
  count(word, sort = TRUE) %>%
  paged_table()

text_df %>%
  filter(word != "flight") %>%
  count(word, sort = TRUE) %>%
  filter(n > 400) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```

## Plot word cloud - Just for Michael
```{r  echo=FALSE}
text_df %>%
  filter(word != "flight") %>%
  count(word) %>%
  with(wordcloud(word, n, scale=c(4,0.5),max.words = 50))
```